<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tgm_downloads"
 *
 * Auto generated by Extension Builder 2017-01-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TgM Simple Downloads',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Oliver Pfaff',
	'author_email' => 'op@teamgeist-medien.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.1.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);